### ISSUE TITLE
NoClassDefFoundError in 2.3.x devices

### ISSUE THREAD

**Issue by derek-cheung** [intercom/intercom-android#98]
We've started seeing this crash on 2.3.x devices since updating to v1.0.4.

`java.lang.NoClassDefFoundError: android.util.LruCache
	at io.intercom.android.nexus.NexusClient.<init>(SourceFile:21)
	at io.intercom.android.sdk.NexusWrapper.<init>(SourceFile:14)
	at io.intercom.android.sdk.Bridge.<init>(SourceFile:35)
	at io.intercom.android.sdk.Bridge.init(SourceFile:42)
	at io.intercom.android.sdk.gcm.GcmIntentService.onHandleIntent(SourceFile:32)
	at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:59)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:130)
	at android.os.HandlerThread.run(HandlerThread.java:60)`

**Comment by harkin** [comment]
:( looking into why this is happening

**Comment by harkin** [comment]
The flow that could cause this to happen is receiving a gcm notification on gingerbread. But the library doesn't ever register for push if you're on gingerbread so you'll never receive one. 

So the service for handling the gcm notification is being pinged when we don't expect it to. I'm making some changes that will address this, it'll be fixed in the next release
