### ISSUE TITLE
java.lang.NoClassDefFoundError: io.intercom.okhttp3.internal.tls.OkHostnameVerifier

### ISSUE THREAD

**Issue by map-idalo** [intercom/intercom-android#254]
My app will crash right after starting it after I upgraded the sdk from version 1 to 3. This happens only for devices with lower android version like 4.3 and 4.2.1. I tested this with 6.0.1 and 5.1.1 devices and my app seems fine.

## Version info
  - Intercom for Android version:  
compile('io.intercom.android:intercom-sdk:3.+@aar') { 
transitive = true 
}
  - Android OS version: 4.3
  - Android Device: Google Nexus 10

## Expected behavior
App should not crash

## Actual behavior
App crashes on start

## Logs
09-08 10:00:04.074 3344-3344/com.medic52.cases.android E/AndroidRuntime: FATAL EXCEPTION: main
          java.lang.NoClassDefFoundError: io.intercom.okhttp3.internal.tls.OkHostnameVerifier
              at io.intercom.okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:428)
              at io.intercom.android.sdk.nexus.NexusClient.<init>(NexusClient.java:32)
              at io.intercom.android.sdk.nexus.NexusClient.<init>(NexusClient.java:25)
              at io.intercom.android.sdk.NexusWrapper.<init>(NexusWrapper.java:36)
              at io.intercom.android.sdk.NexusWrapper.<init>(NexusWrapper.java:33)
              at io.intercom.android.sdk.Injector.getNexusClient(Injector.java:102)
              at io.intercom.android.sdk.Injector.getLifecycleTracker(Injector.java:180)
              at io.intercom.android.sdk.Injector.initWithAppCredentials(Injector.java:61)
              at io.intercom.android.sdk.RealIntercom.<init>(RealIntercom.java:61)
              at io.intercom.android.sdk.Intercom.initialize(Intercom.java:43)
              at com.medic52.cases.android.Medic52App.initialize(Medic52App.java:52)
              at com.medic52.cases.android.Medic52App.onCreate(Medic52App.java:25)
              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
              at android.app.ActivityThread.access$1300(ActivityThread.java:141)
              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
              at android.os.Handler.dispatchMessage(Handler.java:99)
              at android.os.Looper.loop(Looper.java:137)
              at android.app.ActivityThread.main(ActivityThread.java:5103)
              at java.lang.reflect.Method.invokeNative(Native Method)
              at java.lang.reflect.Method.invoke(Method.java:525)
              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
              at dalvik.system.NativeStart.main(Native Method)

**Comment by harkin** [comment]
Hi @map-idalo 

Do you have multidexing enabled for your app?

**Comment by map-idalo** [comment]
HI @harkin 

Yeah multidexing is enabled

**Comment by harkin** [comment]
@map-idalo It sounds like you don't have multidex set up properly for pre Lollipop devices. Can you check to make sure you're using version 1.0.1 of the support multidex library and that you're extending/using the support MultiDexApplication?

**Comment by map-idalo** [comment]
@harkin 

I researched about your suggestion and I successfully build the app now. Thank you for your help.

If anyone is having a similar issue, overriding this to the Application class resolved it for me.


    @Override
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
    }

**Comment by harkin** [comment]
Here's [another link](https://developer.android.com/studio/build/multidex.html#mdex-gradle) for context. @map-idalo if you aren't overriding the application class currently you can use `android.support.multidex.MultiDexApplication` in your manifest
