### ISSUE TITLE
java.lang.NoClassDefFoundError: io.intercom.android.nexus.NexusSocket

### ISSUE THREAD

**Issue by danikula** [intercom/intercom-android#70]
SDK version 0.9.7, Android 5.1, Nexus 5.

After updating to 0.9.7 my app crashes every time I start new activity with stacktrace
```
05-04 19:04:37.724  24282-24282/com.edufii I/Intercom-Android﹕ INFORMATION: Successfully registered or updated user
05-04 19:04:37.741  24282-24282/com.edufii I/art﹕ Rejecting re-init on previously-failed class java.lang.Class<io.intercom.android.nexus.NexusSocket>
05-04 19:04:37.741  24282-24282/com.edufii D/AndroidRuntime﹕ Shutting down VM
05-04 19:04:37.742  24282-24282/com.edufii E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.edufii, PID: 24282
    java.lang.NoClassDefFoundError: io.intercom.android.nexus.NexusSocket
            at io.intercom.android.nexus.NexusClient.connect(NexusClient.java:38)
            at io.intercom.android.sdk.NexusWrapper.connect(NexusWrapper.java:17)
            at io.intercom.android.sdk.NexusWrapper.cycle(NexusWrapper.java:31)
            at io.intercom.android.sdk.identity.AppConfig.update(AppConfig.java:116)
            at io.intercom.android.sdk.identity.AppIdentity.updateAppConfig(AppIdentity.java:56)
            at io.intercom.android.sdk.identity.IdentityStore.setAppConfig(IdentityStore.java:55)
            at io.intercom.android.sdk.api.CallbackHolder.updateAppConfig(CallbackHolder.java:113)
            at io.intercom.android.sdk.api.CallbackHolder.updateBaseResponseObjects(CallbackHolder.java:105)
            at io.intercom.android.sdk.api.CallbackHolder.access$000(CallbackHolder.java:28)
            at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:44)
            at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:41)
            at io.intercom.android.sdk.api.Api$1.success(Api.java:169)
            at io.intercom.android.sdk.api.Api$1.success(Api.java:165)
            at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
            at android.os.Handler.handleCallback(Handler.java:739)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5254)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

SDK 0.9.6 doesn't have this problem. 

My `build.gradle`:
```
repositories {
    maven { url 'http://dl.bintray.com/intercom/intercom-maven' }
}

dependencies {
    compile ('io.intercom.android:intercom-sdk:0.9.7@aar') {
        transitive = true
    }
}
```

I use proguard for shrinking build, but my proguard config doesn't contain any intercom-specific rules.

**Comment by Harkin** [comment]
You don't need any Intercom specific rules in your file, we specify proguard rules for ourselves with a `consumerProguardFiles` line in our build.gradle. That's the theory at least, I'm looking into why it isn't working now. I've confirmed that the .class files actually are in the .aar that's hosted on bintray.

The .pom file for 0.9.7 seems to have gotten corrupted/lost since we uploaded it to bintray (going (here)[consumerProguardFiles] gives an unusual 'requested path not found' error). It's in a weird limbo state where bintray is displaying it (and thus knows it exists) but doesn't seem to want to serve it out. I'm not sure if it's related to this issue though.

**Comment by Harkin** [comment]
I've reuploaded the .pom file and confirmed in a sample app that I can currently build it with the Intercom SDK included. 

@danikula You'll need to clear your local maven cached copy to get that. The quick and easy way is to change your build.gradle dependency to compile `io.intercom.android:intercom-sdk:0.9.+@aar`, do a clean build, and than switch back to  compiling `io.intercom.android:intercom-sdk:0.9.7@aar`.

Could you do that and let me know if you're still experiencing the crash? I haven't been able to reproduce it here in any of my sample apps with Proguard turned on or off (and I can see that the NexusSocket class is doing it's thing).

**Comment by danikula** [comment]
@Harkin :+1: It helps! Thanks.
