### ISSUE TITLE
App crash after updating SDK

### ISSUE THREAD

**Issue by madhurtewani-wow** [intercom/intercom-android#73]
After updating intercom SDK for android app from v0.9.1 to v0.9.8 (tried even with v0.9.4 & v0.9.7), app was crashing with the following error:

```
java.lang.NoClassDefFoundError: io.intercom.android.nexus.NexusSocket
	at io.intercom.android.nexus.NexusClient.connect(NexusClient.java:38)
	at io.intercom.android.sdk.NexusWrapper.connect(NexusWrapper.java:17)
	at io.intercom.android.sdk.NexusWrapper.cycle(NexusWrapper.java:31)
	at io.intercom.android.sdk.identity.AppConfig.update(AppConfig.java:110)
	at io.intercom.android.sdk.identity.AppIdentity.updateAppConfig(AppIdentity.java:56)
	at io.intercom.android.sdk.identity.IdentityStore.setAppConfig(IdentityStore.java:55)
	at io.intercom.android.sdk.api.CallbackHolder.updateAppConfig(CallbackHolder.java:113)
	at io.intercom.android.sdk.api.CallbackHolder.updateBaseResponseObjects(CallbackHolder.java:105)
	at io.intercom.android.sdk.api.CallbackHolder.access$000(CallbackHolder.java:28)
	at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:44)
	at io.intercom.android.sdk.api.CallbackHolder$2.success(CallbackHolder.java:41)
	at io.intercom.android.sdk.api.Api$1.success(Api.java:169)
	at io.intercom.android.sdk.api.Api$1.success(Api.java:165)
	at retrofit.CallbackRunnable$1.run(CallbackRunnable.java:45)
	at android.os.Handler.handleCallback(Handler.java:739)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:135)
	at android.app.ActivityThread.main(ActivityThread.java:5254)
	at java.lang.reflect.Method.invoke(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:372)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
```

On un-install android app (with intercom SDK v0.9.1) & re-install android app (with intercom v0.9.8), android app worked without crashing.

**Comment by danikula** [comment]
[Similar issue](https://github.com/intercom/intercom-android/issues/70)

**Comment by madhurtewani-wow** [comment]
@danikula, the solution is for gradle and I use eclipse. Can you please provide solution for eclipse?

**Comment by Harkin** [comment]
Same symptom but different issue I suspect. 

Can you reproduce this @madhurtewani-wow or is it completely resolved after you uninstalled and reinstalled the app?

**Comment by madhurtewani-wow** [comment]
@Harkin resolved after un-install & re-install. But reproducible if trying again without un-install & re-install.

**Comment by Harkin** [comment]
Okay I can reproduce this myself. We're going to look into this now and we'll update this issue as soon as we know something about this crash

**Comment by Harkin** [comment]
@madhurtewani-wow can you check that you're including all of the necessary dependencies, in particular  `okhttp-ws-2.3.0.jar`?

**Comment by madhurtewani-wow** [comment]
Thanks @Harkin, that was the problem. ```okhttp-ws-2.3.0.jar``` was by mistake missed to include.
