### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Lio/intercom/android/commons/utilities/DeviceUtils

### ISSUE THREAD

**Issue by Mathbl** [intercom/intercom-android#134]
I have this stack after upgrading to 1.1.5. It seems to happen when debugging only.

```
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.agendrix.android, PID: 29861
E/AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lio/intercom/android/commons/utilities/DeviceUtils;
E/AndroidRuntime:     at io.intercom.android.sdk.gcm.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:21)
E/AndroidRuntime:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609)
E/AndroidRuntime:     at android.app.ActivityThread.access$1700(ActivityThread.java:151)
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime:  Caused by: java.lang.ClassNotFoundException: Didn't find class "io.intercom.android.commons.utilities.DeviceUtils" on path: DexPathList[[zip file "/data/app/com.agendrix.android-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
E/AndroidRuntime:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
E/AndroidRuntime:     at io.intercom.android.sdk.gcm.GcmBroadcastReceiver.onReceive(GcmBroadcastReceiver.java:21) 
E/AndroidRuntime:     at android.app.ActivityThread.handleReceiver(ActivityThread.java:2609) 
E/AndroidRuntime:     at android.app.ActivityThread.access$1700(ActivityThread.java:151) 
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1380) 
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5254) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698) 
E/AndroidRuntime:   Suppressed: java.lang.ClassNotFoundException: io.intercom.android.commons.utilities.DeviceUtils
E/AndroidRuntime:     at java.lang.Class.classForName(Native Method)
E/AndroidRuntime:     at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
E/AndroidRuntime:     at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
E/AndroidRuntime:     at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
E/AndroidRuntime:         ... 12 more
E/AndroidRuntime:  Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by harkin** [comment]
Looks like a library didn't get namespaced correctly, I'm investigating our build scripts now to see what went wrong. We'll hotfix this very quickly

**Comment by Mathbl** [comment]
Good, I revert to 1.1.4 for now. Keep in touch.

**Comment by harkin** [comment]
Yeah it was an improperly configured build script. 1.1.6 is on the way, within the next 10 minutes

**Comment by harkin** [comment]
1.1.6 is out now and will fix this for you

**Comment by Mathbl** [comment]
:+1:
